### ISSUE TITLE
Search box on the demo has broken CSRF

### ISSUE THREAD

**Issue by ellieayla** [oprblackout/beres#2]
1. Open https://beres-online.herokuapp.com/beres/ in iOS Safari
2. Type "Amazon" and hit return
3. Error:

>Forbidden (403)
CSRF verification failed. Request aborted.
You are seeing this message because this site requires a CSRF cookie when submitting forms. This cookie is required for security reasons, to ensure that your browser is not being hijacked by third parties.
If you have configured your browser to disable cookies, please re-enable them, at least for this site, or for 'same-origin' requests.

**Comment by feldrim** [comment]
Same with Chrome on Android.

**Comment by josephlane** [comment]
This issue has been resolved. Thanks for the feedback guys.

<img width="1204" alt="screen shot 2018-02-04 at 1 34 00 pm" src="https://user-images.githubusercontent.com/1155601/35781517-bbceb224-09b0-11e8-9126-fa7529eab179.png">
